/** Fixed copy from browser failure boundaries; dynamic names and unknown text stay private. */
const ACTIONS = new Set([
  "Couldn't accept the invite",
  "Couldn't add local directory",
  "Couldn't add the agent to this Space",
  "Couldn't answer the connection request",
  "Couldn't apply this revision",
  "Couldn't approve the terminal sign-in",
  "Couldn't attach the file",
  "Couldn't cancel deletion",
  "Couldn't change automatic assignment",
  "Couldn't change the GitHub account",
  "Couldn't change who can join",
  "Couldn't change who can read this page",
  "Couldn't change who edits this page",
  "Couldn't check deletion requirements",
  "Couldn't check deletion status",
  "Couldn't check whether this app is up to date",
  "Couldn't complete the purchase",
  "Couldn't confirm the recovery",
  "Couldn't confirm the transfer",
  "Couldn't create the Space",
  "Couldn't create the invite code",
  "Couldn't create the page",
  "Couldn't decide this request",
  "Couldn't delete secret",
  "Couldn't delete the Space",
  "Couldn't delete the evaluator lineage",
  "Couldn't delete this page",
  "Couldn't delete your account",
  "Couldn't disable the agent",
  "Couldn't discover local agents",
  "Couldn't hand the session to your terminal",
  "Couldn't import workspace",
  "Couldn't install xMatrix update",
  "Couldn't join this Space",
  "Couldn't leave the Space",
  "Couldn't load App Store products",
  "Couldn't load Automations",
  "Couldn't load GitHub accounts",
  "Couldn't load app actions",
  "Couldn't load app connections",
  "Couldn't load apps",
  "Couldn't load channels",
  "Couldn't load earlier messages",
  "Couldn't load launch targets",
  "Couldn't load messages",
  "Couldn't load platform data",
  "Couldn't load registered locations",
  "Couldn't load routing decisions",
  "Couldn't load secrets",
  "Couldn't load the agent list",
  "Couldn't load the credentials",
  "Couldn't load this access request",
  "Couldn't load this agent",
  "Couldn't load this file",
  "Couldn't load this secret request",
  "Couldn't load transfer proposals",
  "Couldn't load your Spaces",
  "Couldn't load your workspace",
  "Couldn't move this Space to pages",
  "Couldn't name this machine",
  "Couldn't open the thread",
  "Couldn't open this channel link",
  "Couldn't open this invite",
  "Couldn't prepare a setup command",
  "Couldn't prepare the message",
  "Couldn't propose the move",
  "Couldn't read this machine's name",
  "Couldn't record your decision",
  "Couldn't refresh the local daemon session",
  "Couldn't remove local directory",
  "Couldn't remove the Machine",
  "Couldn't remove your photo",
  "Couldn't rename the Machine",
  "Couldn't rename the Space",
  "Couldn't rename the channel",
  "Couldn't rename the page",
  "Couldn't request the sign-in",
  "Couldn't request the summary",
  "Couldn't restart the Agent",
  "Couldn't restore the Space",
  "Couldn't restore the purchase",
  "Couldn't save secret",
  "Couldn't save setup status",
  "Couldn't save the credentials",
  "Couldn't save the harness switch",
  "Couldn't save the secret",
  "Couldn't send that to the machine",
  "Couldn't send the invite",
  "Couldn't send the message",
  "Couldn't send the question",
  "Couldn't send the request to the Agent",
  "Couldn't send your answer",
  "Couldn't sign you in",
  "Couldn't start",
  "Couldn't start agent",
  "Couldn't start drafting pages",
  "Couldn't start the Agent",
  "Couldn't start the agent",
  "Couldn't start the agent.",
  "Couldn't start the conversation",
  "Couldn't switch environments",
  "Couldn't update member permissions",
  "Couldn't update the Automation",
  "Couldn't update the agent",
  "Couldn't update the member",
  "Couldn't update the message",
  "Couldn't update your photo",
  "Couldn't update your profile",
  "Couldn't upload the file",
  "Couldn't use that folder",
]);

/** Accept only an exact source-defined action, never arbitrary provider tag text. */
export function sentryBrowserAction(value: string): string | undefined {
  const action = value.slice("browser: ".length);
  return ACTIONS.has(action) ? action : undefined;
}
